In [ ]:
import numpy as np
# Vector

a = np.array([10, 20, 30])
b = np.array([1, 77, 2, 3, 4, 5, 8, 11])
print(b[1:4])
print(b[0:7:2])

[77  2  3]
[1 2 4 8]


In [ ]:
for i in range(1, 2, 5):
  print(i)
i = 1
# while i < 5:
  # print(i)
  # i += 2

In [ ]:
# Matrix
a = np.array([[10, 20, 30], [40, 50, 60]])
print(a)

[[10 20 30]
 [40 50 60]]


In [ ]:
# Slicing
print(a[1][2])
print(a[1,2])
print(a[0:,2])
print(a[0, 0:-1])

60
60
[30 60]
[10 20]


In [ ]:
# Shape
print(a.shape)

(2, 3)


In [ ]:
# Initialize all elements
a = np.full((5, 3), 7)
print(a)

[[7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Zeros
a = np.zeros((4, 3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Empty elements
a=  np.empty((4, 4))
print(a)

[[ 4.87055240e-310  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [-4.10011613e-121  0.00000000e+000  0.00000000e+000  1.93412245e-261]
 [ 0.00000000e+000  0.00000000e+000  1.59896178e+252  0.00000000e+000]
 [ 0.00000000e+000 -4.10011613e-121  6.88024035e-310  6.88023339e-310]]


In [ ]:
# Random elements
b=  np.random.random((2 ,3))
print(b)


[[0.91797099 0.04106853 0.6105724 ]
 [0.1957541  0.2584983  0.53914497]]


In [ ]:
# Range to array
a = np.arange(10, 50, 5)
print(a)

[10 15 20 25 30 35 40 45]


In [ ]:
a = np.arange(10, 50, 5)
b = a.copy()
print(a)
print(b)
a[1] = 2
print(a)
print(b)

[10 15 20 25 30 35 40 45]
[10 15 20 25 30 35 40 45]
[10  2 20 25 30 35 40 45]
[10 15 20 25 30 35 40 45]


In [ ]:
# Element wise operations
c = a + b
print(a)
print(b)
print(c)
print(a + 2)

[10  2 20 25 30 35 40 45]
[10 15 20 25 30 35 40 45]
[20 17 40 50 60 70 80 90]
[12  4 22 27 32 37 42 47]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
print(A)
print(B)
# Elementwise multiplication
print(A*B)

# Matrix multiplication
print(A @ B)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [ ]:
a = np.full((3, 4), 5)
print(a)
b = np.full((3, 4), 7)
print(b)
c = np.concatenate((a, b), axis=0)
print(f"concatenate:\n {c}")
d = np.vstack((a, b))
print(f"vstack:\n {d}")
d = np.hstack((a, b))
print(f"hstack:\n {d}")

d = np.stack((a, b))
print(f"stack:\n {d}")
print(d.shape)
d = np.reshape(d, (6, 4))
print(d.shape)
print(f"reshaped:\n{d}")
# Copy
t = d.flatten()
print(f"flattened:{0}\n", t)
t[0] = 1
print(f"flattened:{0}\n", t)
# View
v = d.ravel()
print(f"ravel:{0}\n", v)
v[0] = 2
print(f"ravel:{0}\n", v)
print(d)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
concatenate:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
vstack:
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
hstack:
 [[5 5 5 5 7 7 7 7]
 [5 5 5 5 7 7 7 7]
 [5 5 5 5 7 7 7 7]]
stack:
 [[[5 5 5 5]
  [5 5 5 5]
  [5 5 5 5]]

 [[7 7 7 7]
  [7 7 7 7]
  [7 7 7 7]]]
(2, 3, 4)
(6, 4)
reshaped:
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
flattened:0
 [5 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 7]
flattened:0
 [1 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 7]
ravel:0
 [5 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 7]
ravel:0
 [2 5 5 5 5 5 5 5 5 5 5 5 7 7 7 7 7 7 7 7 7 7 7 7]
[[2 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [ ]:
d = np.linspace(10, 100, 12)
dResh = d.reshape((3, 4))

print(d)
print(dResh)
# a = [1, 2, 3, 4, 5]
# print(np.mean(a))
# print(np.std(a))

# b = [100, 100, 300, 500, 500]
# print(np.mean(b))
# print(np.std(b))
# print("a standardized", (a - np.mean(a)) / np.std(a))
# print("b standardized", (b - np.mean(b)) / np.std(b))
print(np.mean(dResh, axis=0))
print(np.std(dResh, axis=0))
print(f"sub{0}", (dResh - np.mean(dResh, axis=0))/np.std(dResh, axis = 0))

[ 10.          18.18181818  26.36363636  34.54545455  42.72727273
  50.90909091  59.09090909  67.27272727  75.45454545  83.63636364
  91.81818182 100.        ]
[[ 10.          18.18181818  26.36363636  34.54545455]
 [ 42.72727273  50.90909091  59.09090909  67.27272727]
 [ 75.45454545  83.63636364  91.81818182 100.        ]]
[42.72727273 50.90909091 59.09090909 67.27272727]
[26.72170628 26.72170628 26.72170628 26.72170628]
sub0 [[-1.22474487e+00 -1.22474487e+00 -1.22474487e+00 -1.22474487e+00]
 [ 0.00000000e+00 -2.65904702e-16  2.65904702e-16  5.31809405e-16]
 [ 1.22474487e+00  1.22474487e+00  1.22474487e+00  1.22474487e+00]]


In [ ]:
print((0.1 + 0.2) == 0.3)

False


In [ ]:
# 1. Form a numpy array a: [1, 3, 5, 7, 9, 11] using np.arange.
# 2. Print a array consisting of every second element in a using numpy slicing.
# 3. Create array of 15 equally spaced elemnts from 10 to 100, then reshape them to 5x3 and standardize the data by columns.